### ISSUE TITLE
Feature: Add a option to take snapshot from video

### ISSUE THREAD

**Issue by sharunspi** [cookpete/react-player#1104] opened 2020-12-13 07:20 UTC
### Feature request
Add new method to take the snapshot of video at the current moment.
like
`getCurrentFrame`
this will return bob URL of the current frame

**Comment by cookpete** [comment] 2020-12-26 21:53
Duplicate of https://github.com/cookpete/react-player/issues/341

**Closed by cookpete** 2020-12-26 21:53 UTC
