### ISSUE TITLE
onEnded not being called in some conditions

### ISSUE THREAD

**Issue by floydnoel** [CookPete/react-player#496] opened 2018-10-10 16:31 UTC
I have some video URLs that play fine, but the onEnded callback doesn't get called if loop is set to true.

Here's a reproduction (based on the standalone example):
https://jsfiddle.net/qv68yk2r/

If the loop attribute is removed, onEnded gets called as expected.

**Comment by floydnoel** [comment] 2018-10-10 16:32
Here are some links for reference:

- https://sylvan.apple.com/Videos/comp_A009_C001_010181A_v09_SDR_PS_FINAL_20180725_SDR_2K_AVC.mov
- https://sylvan.apple.com/Videos/comp_A105_C003_0212CT_FLARE_v10_SDR_PS_FINAL_20180711_SDR_2K_AVC.mov
- https://sylvan.apple.com/Videos/comp_LA_A005_C009_PSNK_ALT_v08_SDR_PS_FINAL_20180709_SDR_2K_AVC.mov

**Comment by CookPete** [comment] 2018-10-11 07:43
Seems like a duplicate of https://github.com/CookPete/react-player/issues/471.

The issue is that a browser does not deem a looping video to ever "end", which is technically true.. `onEnded` should fire when a video ends, and a looping video never really ends. 

The only reason `onEnded` fires for _some_ players is when that player doesn't support `loop` natively, so ReactPlayer listens for `onEnded` and immediately seeks to the start of the video.

I don't know what we can do, other than maybe prevent `onEnded` being called altogether when `loop` is true, and instead have an `onLoop` callback prop that is checked during the `onProgress` callback to see if the current position has moved from the end to the start.

**Comment by floydnoel** [comment] 2018-10-11 21:10
Thanks for the reply and explanation. I managed to work around the behavior for my use case. The only reason I raised an issue is because the behavior is inconsistent between videos. I would suggest to at least put a small note in the callback prop documentation such as "`onEnded` callback is not guaranteed to be called for videos where `loop` is set to `true`."

Perhaps all videos could be looped by the same method (e.g. using `seekTo(0)`), which would allow onEnded to always be called. Or, as you say, `onEnded` could be suppressed when it shows up with a `loop`, and another callback introduced for that purpose (or perhaps, document that there is no support for using `onEnded` and `loop` together).

Since `onEnded` can be relied upon when `loop` is disabled, and since `loop` can be simulated with `seekTo(0)`, there is no missing functionality as far as I am concerned. Therefore in my view it would be quite sufficient to add a little note in the documentation.

Thank you again for the reply, and for working on this great and useful component! Please let me know if there is anything I can do to help.

**Closed** 2018-11-17 18:38 UTC
