### ISSUE TITLE
seeking by clicking on timeline pauses video

### ISSUE THREAD

**Issue by oldo** [cookpete/react-player#1154] opened 2021-01-27 03:56 UTC
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
When clicking on timeline to seek to a different part of video the `onPause` event is triggered, pausing the video.

#### Expected Behavior
If the video is already playing then I'd expect to just click on the timeline, video will seek and continue playing from there.

#### Steps to Reproduce
1. Create file player
2. click on the timeline to seek to a different location on the video
3. video pauses.

#### Environment
- URL attempting to play: N/A
- Browser: Chrome
- Operating system: macOS

**Comment by cookpete** [comment] 2021-01-27 09:32
Duplicate of https://github.com/cookpete/react-player/issues/1151

**Closed by cookpete** 2021-01-27 09:32 UTC
