### ISSUE TITLE
Minified React error #130 

### ISSUE THREAD

**Issue by jiahuamld** [cookpete/react-player#1831] opened 2024-04-24 07:31 UTC
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.
   <ReactPlayer
              ref={playerRef}
              width={'100%'}
              height={'520px'}
              url={D.video.videoUrl}
              playing={D.isPlaying}
              // controls
              // onPlay={() => setD((draft) => ({ ...draft, isPlaying: true }))}
              onEnded={() => {
                console.log('视频播放已完成') // 当前的视频数据 接口设置学完 记录学习进度等
              }}
            />
#### Current Behavior

![image](https://github.com/cookpete/react-player/assets/11866846/a377ed14-d3a3-4593-9c47-47438a8ea2be)

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by jiahuamld** [comment] 2024-04-24 07:31
import ReactPlayer from 'react-player'

**Comment by jiahuamld** [comment] 2024-04-24 07:31
当这个组件渲染时 报错130

**Comment by luwes** [comment] 2024-04-24 14:28
duplicate of #1746

**Closed by luwes** 2024-04-24 14:28 UTC
