### ISSUE TITLE
onVolumeChange event needed

### ISSUE THREAD

**Issue by seleckis** [cookpete/react-player#1181] opened 2021-02-22 11:45 UTC
#### Current Behavior
Player does not have volume change event listener.

#### Expected Behavior
Player fires event every time volume control changes of the native player (<video> tag).

#### Steps to Reproduce
1. Enable controls in Demo: https://cookpete.com/react-player/
2. Choose HLS (m3u8) source
3. Change volume in the native player
4. Custom volume range element does not change its value.

#### Environment
- URL attempting to play: https://cookpete.com/react-player/
- Browser: Safari/Chrome
- Operating system: MacOS

#### Other Information
volumechange event has support in all browsers: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volumechange_event

My case: I have a custom player controls. Switching player to fullscreen, the native player controls are shown. Changing volume there and returning back from fullscreen the volume control value is wrong, because it cannot be updated.

**Comment by cookpete** [comment] 2021-02-22 11:56
Duplicate of https://github.com/cookpete/react-player/issues/1109

**Closed by cookpete** 2021-02-22 11:56 UTC

**Comment by seleckis** [comment] 2021-02-22 13:01
I see, but thought it is not related. I'm talking about built-in <video> tag functionality which is cross-browser supported. Do you really think that if some CUSTOM player does not support common functionality, the player should not support it at all?
