### ISSUE TITLE
 React Player is giving error while loading the google drive videos

### ISSUE THREAD

**Issue by prayastyagi** [cookpete/react-player#1733] opened 2024-01-17 13:26 UTC
#### Current Behavior
 React Player is giving error while loading the google drive videos but i can open the same video link in an iframe.

#### Expected Behavior
Google drive videos should play without giving any error as it used to play earlier.

#### Steps to Reproduce
1. Open https://cookpete.com/react-player
2. Enter `https://drive.google.com/file/d/1bIvt1KO_nYUV4PUUoKFSSKZHEC3Qfeyn/preview` in Custom URL
3. Click on `Load` button.
4. Error is thrown in the console and video doesn't play.

**Comment by luwes** [comment] 2024-01-26 13:18
duplicate of https://github.com/cookpete/react-player/issues/1678

**Closed by luwes** 2024-01-26 13:18 UTC
