### ISSUE TITLE
Full-screen callback?

### ISSUE THREAD

**Issue by mgoldenbe** [cookpete/react-player#1352] opened 2021-11-10 22:20 UTC
I need a way to programmatically find out whether `react-player` is in full-screen mode, so I can save this preference for future video playbacks. Is there a way to do this? 

P.S. I have also asked this question at [stackoverflow](https://stackoverflow.com/q/69897509/), but received no replies there.

**Comment by cookpete** [comment] 2022-02-21 14:49
Duplicate of https://github.com/cookpete/react-player/issues/390

**Closed by cookpete** 2022-02-21 14:50 UTC
