### ISSUE TITLE
Setting `progressInterval` to less than 1000ms does not work for Twitch videos

### ISSUE THREAD

**Issue by RusseII** [cookpete/react-player#1206] opened 2021-04-03 11:13 UTC
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

Setting onProgress interval for any value less than 1000 has no effect. Setting it to a higher value (like 5000ms) does work.
#### Expected Behavior

I should be able to set progressInterval to 100ms and have it call my `onProgress` function every 100ms
#### Steps to Reproduce

1. Visit my jsFiddle below
1. Look at the console logs, you will notice each callback happens every 1000ms instead of 100ms

#### Environment
- URL attempting to play: https://www.twitch.tv/videos/971833140
- Browser: Chrome
- Operating system: MacOS catalina
- jsFiddle example: https://jsfiddle.net/8rq3726h/9/

**Comment by gatesyp** [comment] 2021-05-15 23:20
Hello, any update on this? Seeing the same exact issue on my end. Will be investigating more.

**Comment by RusseII** [comment] 2021-06-11 12:02
Does anyone have any ideas? If someone can point me in the right direction of what the issue is I can investigate and try and fix. I'm also willing to put a $100 bounty on this for a pr that fixes the issue :) 

@cookpete @gatesyp

**Comment by marcoburrometo** [comment] 2021-06-29 10:08
I have the same problem, not for Vimeo only, but for every source. Callback gets called, but value is the same

**Comment by cookpete** [comment] 2021-06-29 21:51
@RusseII Turns out the problem is pretty simple:

- The `getCurrentTime` method of the Twitch player only updates the value every second. 
- `onProgress` is not fired if the values are the same as the previous call, to prevent needless re-rendering.

See below for a console log of the result of `getCurrentTime()` every 0.5 seconds. Notice that the value returned doesn't increase by ~0.5 each time, but is the same value until roughly a second has passed.

![image](https://user-images.githubusercontent.com/1926029/123871413-a16c9100-d92b-11eb-8327-c0fd0a6e6fd3.png)

**Comment by RusseII** [comment] 2021-07-02 17:50
Sounds like this issue is caused by twitch and can't be fixed by react-player ?

**Closed** 2024-04-20 12:08 UTC
