### ISSUE TITLE
'postMessage' on 'DOMWindow' for YouTube

### ISSUE THREAD

**Issue by Sam-Moradi** [cookpete/react-player#1397] opened 2022-02-09 22:51 UTC
Hello,
If I use YouTube video on react player on my own domain ( eample.com) then U get the following error as the below.

`www-widgetapi.js:915 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin (https://example.com)`

In the reactPlayer component, I added the configure for YoutTube but it did not help 

`<ReactPLayer     config={{ youtube: { playerVars: { enablejsapi: 1,origin:"https://example.com" }}}} .....`

Does it look it is a bug that does override the iframe configure of  YouTube?

**Comment by cookpete** [comment] 2022-02-19 13:17
Duplicate of #508

**Closed by cookpete** 2022-02-19 13:17 UTC

**Comment by andy-milian** [comment] 2022-11-04 22:34
I was able to solve the issue after reading about the widget_referrer parameter in the YouTube documentation ([here](https://developers.google.com/youtube/player_parameters?playerVersion=HTML5#widget_referrer))

"This parameter identifies the URL where the player is  embedded. This value is used in YouTube Analytics reporting when the  YouTube player is embedded in a widget, and that widget is then embedded  in a web page or application. In that scenario, the origin  parameter identifies the widget provider's domain, but YouTube  Analytics should not identify the widget provider as the actual traffic  source. Instead, YouTube Analytics uses the widget_referrer parameter value to identify the domain associated with the traffic source."

EXAMPLE:


```
<ReactPlayer
    url='https://www.youtube.com/{your-video-id}'
    config={{
      youtube: {
          playerVars: {
              widget_referrer: 'https://{your-domain}'
          }
      }
  }}
/>
```

That will make the request go like this:

`
https://www.youtube.com/embed/{your-video-id}?autoplay=0&mute=0&controls=1&origin=https%3A%2F%2F{your-domain}&playsinline=1&showinfo=0&rel=0&iv_load_policy=3&modestbranding=1&widget_referrer=https%3A%2F%2F{your-domain}&enablejsapi=1&widgetid=1`

An then the **widgetapi.js** will stop complaining.

Cheers!

**Comment by pieroguerrero** [comment] 2023-01-10 00:22
> I was able to solve the issue after reading about the widget_referrer parameter in the YouTube documentation ([here](https://developers.google.com/youtube/player_parameters?playerVersion=HTML5#widget_referrer))
> 
> "This parameter identifies the URL where the player is embedded. This value is used in YouTube Analytics reporting when the YouTube player is embedded in a widget, and that widget is then embedded in a web page or application. In that scenario, the origin parameter identifies the widget provider's domain, but YouTube Analytics should not identify the widget provider as the actual traffic source. Instead, YouTube Analytics uses the widget_referrer parameter value to identify the domain associated with the traffic source."
> 
> EXAMPLE:
> 
> ```
> <ReactPlayer
>     url='https://www.youtube.com/{your-video-id}'
>     config={{
>       youtube: {
>           playerVars: {
>               widget_referrer: 'https://{your-domain}'
>           }
>       }
>   }}
> />
> ```
> 
> That will make the request go like this:
> 
> ` https://www.youtube.com/embed/{your-video-id}?autoplay=0&mute=0&controls=1&origin=https%3A%2F%2F{your-domain}&playsinline=1&showinfo=0&rel=0&iv_load_policy=3&modestbranding=1&widget_referrer=https%3A%2F%2F{your-domain}&enablejsapi=1&widgetid=1`
> 
> An then the **widgetapi.js** will stop complaining.
> 
> Cheers!

Just to inform that this solution is not working for me.
I have tried placing the 'widget_referrer' property in the 'playerVars' object and also in the 'embedOptions' one.
BTW I have read several posts about this including chatGPT, but no success. 
Will continue looking around.
