### ISSUE TITLE
React Player is not Working in Safari for all the video format

### ISSUE THREAD

**Issue by krishnadmass** [cookpete/react-player#1305] opened 2021-09-02 06:53 UTC
when using ReactPlayer the video is not playing in safari browser only and it shows like broken player it does not catch the error in onError handler, and the video is working fine in all other browsers(chrome, firefox, opera) is there any solution to solve this?

**Comment by cookpete** [comment] 2021-09-02 18:49
What format is the file you are trying to play? Sounds like a duplicate of https://github.com/cookpete/react-player/issues/1158

**Comment by krishnadmass** [comment] 2021-09-03 04:39
> What format is the file you are trying to play? Sounds like #1158

tried with mp4 and webm it not playing in safari only

**Comment by worstestes** [comment] 2021-10-05 19:20
Currently facing the same issue with _all_ video formats for safari, chrome/firefox seem to have no issues. Any tips here?

**Comment by aroolinks** [comment] 2022-05-16 19:45
Currently facing the same issue with all video formats for safari, any solution? How we can sort it out?

**Comment by paul-bg** [comment] 2022-06-13 18:47
I have the same issue the player work well in chrome and Firefox but in safari Mac or iOS it appears with a blocked player

here the link of the implementation 
https://xdsea.com/nft/0x85d216d87C993c250A7725aF8f6C161d0504c32B/1673

and its weird cause the demo page works in Mac and Iphone safari 


<img width="586" alt="Screen Shot 2022-06-13 at 13 46 20" src="https://user-images.githubusercontent.com/22463926/173423350-40fd1c42-6c93-4a47-83b8-7ec6c762dd57.png">

**Comment by reynoldsnlp** [comment] 2022-06-29 17:19
@paul-bg I am having a similar problem. I'm just getting started with debugging, but it looks like this blog post might be helpful: https://blog.logrocket.com/streaming-video-in-safari/

**Comment by daniel-j-dev** [comment] 2022-07-11 14:36
Similar problem - can't play .ogg files on Safari

**Comment by cookpete** [comment] 2022-07-11 19:41
Looks like [ogg support is not great on Safari](https://caniuse.com/ogg-vorbis).

I’m gonna close this for now as it just seems like issues with Safari video support.

If anyone can isolate a specific problem with this library, that isn’t just a general support problem with Safari, with steps to reproduce or a jsfiddle/codesandbox, please reopen the issue with more details.

**Closed by cookpete** 2022-07-11 19:41 UTC
Labels: Needs more info

**Comment by PragathiPrabhu** [comment] 2022-11-22 07:09
Can’t play hls video in safari.

**Comment by apoorvdodiya** [comment] 2023-06-25 13:31
In my case
1. there was an issue from backend side, I was reading the the only the start value of the `range` header from the first request which did not matched in the response.

The thing is that Chrome sends range="0-" for the first request and Safari sends range="0-1" so my solution worked for Chrome for the first time and then I identified and fiexed the issue for Safari.

2. After fixing the first issue I could not play `.mkv` files because HTML 5 does not support it.
3.

**Comment by schwarzsky** [comment] 2023-07-07 09:21
Can't play even MP4 videos on safari with no back-end. Just serving files from `public` directory.
