### ISSUE TITLE
Border radius doesnt work on player

### ISSUE THREAD

**Issue by jake-chambers** [cookpete/react-player#1135] opened 2021-01-14 16:03 UTC
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

```
      <ReactPlayer
          style='border-radius:16px'
          //style={{borderRadius:16}}
      />

Neither work
```
#### Expected Behavior
Why doesnt it work

#### Environment
- URL attempting to play: Local video
- Browser: Chrome and Safari
- Operating system: MacOS

**Comment by cookpete** [comment] 2021-01-15 10:18
Duplicate of https://github.com/cookpete/react-player/issues/1134

**Closed by cookpete** 2021-01-15 10:18 UTC
