### ISSUE TITLE
Everything is fine in development mode. The video is not available after the build.

### ISSUE THREAD

**Issue by aon24** [cookpete/react-player#1738] opened 2024-02-12 23:05 UTC
Some videos work after the project is built, but this video(relax music) only plays in development mode:
https://www.youtube.com/watch?v=Z2msUWb6iX4
I tried react-youtube. The same thing. It plays in development, but not after rebuilding

    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-player": "^2.14.1",
    "react-scripts": "5.0.1",

Mozilla, GH
Linux Mint 21

**Comment by jonathastavares** [comment] 2024-02-15 20:51
Exactly the same problem here, getting react minified erro 130 after building.

**Comment by luwes** [comment] 2024-02-22 02:10
could you provide a Codesandbox online? this will help with debugging.

**Comment by saidelimam** [comment] 2024-02-23 11:55
Same issue for me, I got:
`Unexpected Application Error!
Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    `
    
  here's my vite config :
  
  `{
  minify: 'terser', // 'esbuild' by default, 'terser' is slower at build but better compression
			terserOptions: {
				compress: {
					// Terser options for compression
					drop_console: isProduction && !isPreview, // Remove all console statements (log, time..)
					drop_debugger: true, // Remove debugger statements
					passes: 3, // Run the compressor multiple times for better results
					reduce_funcs: true, // Inline single-use functions
					reduce_vars: true, // Inline single-use variables
				},
				format: {
					// Terser options for formatting
					comments: false, // Remove comments
					wrap_iife: true, // Wrap immediate function invocations in parentheses
				},
				mangle: {
					properties: {
						regex: /^_/, // Example: mangle properties starting with underscores
					},
				},
				ecma: 2020,
				module: true,
				toplevel: true,
				safari10: true,
			}
}
`

**Comment by luwes** [comment] 2024-04-20 19:12
duplicate of #1746

**Closed by luwes** 2024-04-20 19:12 UTC
Labels: Needs more info
