### ISSUE TITLE
react-player cannot play multiple source

### ISSUE THREAD

**Issue by donny08** [cookpete/react-player#1411] opened 2022-03-07 07:00 UTC
#### Current Behavior
I am trying to play multiple videos in single video. I passed multiple videos as array in **url** option of react-player, it render only video1 in the player

#### Expected Behavior
Play multiple videos in single video

#### Steps to Reproduce
import ReactPlayer  from 'react-player';

<ReactPlayer url={['http:***/video1.mkv', 'http:***/video2.mkv']}>

#### Environment
- URL attempting to play: 
- Browser:

**Comment by cookpete** [comment] 2022-03-08 11:46
Duplicate of https://github.com/cookpete/react-player/issues/1147

**Closed by cookpete** 2022-03-08 11:46 UTC
