### ISSUE TITLE
Player not loading with multiple sources (vimeo only)

### ISSUE THREAD

**Issue by marcos-nunes-dev** [cookpete/react-player#1364] opened 2021-12-03 17:19 UTC
#### Current Behavior

When I create a playlist with youtube videos the multiple sources works fine. But if I add an Array of Vimeo URLs the player are not being loaded. But if I use the same video as only one source (string) works fine too.

#### Expected Behavior

Use array of vimeo videos as multiple sources.

#### Steps to Reproduce
```
import Player, { ReactPlayerProps } from 'react-player';

<Player url={["https://player.vimeo.com/video/243556536"]}/>

```

**Comment by mirek11s** [comment] 2022-03-03 20:00
Any update on this? I face the same issue but with other services too.

**Comment by cookpete** [comment] 2022-03-14 11:08
Duplicate of https://github.com/cookpete/react-player/issues/1147

**Closed by cookpete** 2022-03-14 11:08 UTC
