### ISSUE TITLE
Tik Tok Support

### ISSUE THREAD

**Issue by vihardesu** [cookpete/react-player#1193] opened 2021-03-14 00:52 UTC
Hey, I'd love if you added Tik Tok support for this project. I'm trying to create Tik Tok collections on my web app. Thanks! would love to know your thoughts on supporting this. Email me at vihardesu@gmail.com

**Comment by walidvb** [comment] 2021-03-22 18:40
I'm not sure I can find an API to control TikTok's video?
If there isn't, then we need to see with @cookpete if this can match the specs of his lib. I have just opened a similar request to #1200 .

Else, maybe by adding a customPlayer? 🤔

**Comment by Maxou44** [comment] 2021-06-29 19:35
There is an embed documentation here: https://developers.tiktok.com/doc/embed-videos

But you can't get play/progress events or interact with it 😥

**Comment by cookpete** [comment] 2021-06-29 22:02
Duplicate of https://github.com/cookpete/react-player/issues/1030

@Maxou44 is correct. There is no point including support for an iframe that does nothing. Just render the iframe in your app.

**Closed by cookpete** 2021-06-29 22:02 UTC

**Comment by OrenMag** [comment] 2022-04-12 10:34
Is there a conclusion regarding this? We would really appreciate a support for native embedded tik tok videos

**Comment by cookpete** [comment] 2022-04-13 09:51
The conclusion is [this](https://github.com/cookpete/react-player/issues/1030#issuecomment-718244567):

>It doesn't look like there is an interactive player API for TikTok videos. There would be no value adding this to ReactPlayer – you may as well just render the standard embed code in your app: https://developers.tiktok.com/doc/Embed

Until TikTok has an interactive player with methods and events, adding `react-player` in your bundle just to render an iframe is completely pointless.

**Comment by rklf** [comment] 2024-10-26 17:27
[up](https://developers.tiktok.com/doc/embed-player) @cookpete

**Comment by Maxou44** [comment] 2025-06-13 19:28
Tiktok added a Embed Player API, more information here : https://developers.tiktok.com/doc/embed-player?enter_method=left_navigation

Can you reopen the issue @cookpete ?

**Comment by ritik-pg** [comment] 2025-07-15 12:55
@cookpete , as @Maxou44 said, tiktok now supports embed player API, can you reopen this issue?

**Comment by ronalduQualabs** [comment] 2025-07-16 17:36
hello @vihardesu Good news. The TikTok media element has been successfully added to the [repo](https://github.com/cookpete/react-player/releases/tag/v3.3.0) and is now available for use! Huge thanks to everyone who suggested it, requested it, and shared valuable info to help us get it working really appreciate the collaboration! 

Please note there are some limitations, as [previously mentioned](https://github.com/cookpete/react-player/issues/1193#issuecomment-3074927676), so be sure to check the docs or notes before integrating it into your projects.

If you run into any issues or have more feedback, feel free to open a new ticket.

[Demo](https://cookpete.github.io/react-player/)

**Comment by ronalduQualabs** [comment] 2025-07-16 17:39
@ritik-pg The `volume_control` its not working as expected from the side could help if you report it [here](https://developers.tiktok.com/support) and the `closed_captions` its an attribute to show or hide their own caption button not to control it by implementation.
