### ISSUE TITLE
how to play video with react-player from spesific path

### ISSUE THREAD

**Issue by genc6541** [cookpete/react-player#1058] opened 2020-10-26 16:48 UTC
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Environment
- URL attempting to play:  "E:\video\xxx.mp4"
- Browser: Chrome
- Operating system: windows

**Comment by cookpete** [comment] 2020-10-27 10:13
Duplicate of https://github.com/cookpete/react-player/issues/1059

**Closed by cookpete** 2020-10-27 10:13 UTC
