### ISSUE TITLE
URL Array Issue

### ISSUE THREAD

**Issue by ravola** [cookpete/react-player#1099] opened 2020-12-06 10:56 UTC
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

I am using react-player 2.3.1
I am passing an array to the 'url' parameter. One is a *.mp4 file (local file) and another is a *.m3u8 file from AWS.
The *.mp4 file is played, however the next video is not called. 

#### Expected Behavior

The *.mp4 file is played, the next video in the array should play.
What am i missing?
#### Steps to Reproduce

1. Pass a local *.mp4 file in the url array along with a remote accessible AWS link to *.m3u8 file
2. Play react-player 
1.

#### Environment
- URL attempting to play: 
- Browser: Chrome (86.0.4240.198)
- Operating system: Windows 10
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

#### Other Information

url -> is from AWS. 
The Intro is played, Intro3D and url from AWS is not played
<ReactPlayer controls="true" playing="true"
        url={[Intro,Intro3D,url]} 
        controls width="100%" height="500px" />

**Comment by afzaalahmad** [comment] 2020-12-07 21:54
@ravola possible reason that I can determine from the given information is that it can be due to cors policy of s3 bucket or resource that you are using for video serving.
It would be helpful if you can share the links here, specifically aws link of a video. Otherwise, check your console for cors error, if any.

**Comment by ravola** [comment] 2020-12-08 02:58
@afzaalahmad the AWS S3 cors policy is setup and it plays from S3 when i pass the url without an array.
url={url} --> url = AWS S3 link which works.
<ReactPlayer url={url} playing="true" />

When i pass an array
var video = "../../video.mp4" -->video.mp4
<ReactPlayer url={[video, url]} playing="true" />

The video.mp4 plays and url (AWS m3u8) will not start.

**Comment by cookpete** [comment] 2020-12-08 22:28
Duplicate of #1053

**Closed** 2020-12-08 22:28 UTC

**Comment by ravola** [comment] 2020-12-09 04:04
@cookpete do you plan to support a playlist for this scenario? I can see it works for youtube as a playlist. Why not for this scenario?
Trying to understand why it wouldn't work?

**Comment by cookpete** [comment] 2020-12-09 09:23
It works for youtube because the youtube player supports passing in a list of video IDs to generate a playlist. ReactPlayer just acts as a proxy to that functionality.

Playlist supports comes up a lot and is simply beyond the scope of this component. There is nothing stopping anyone creating `ReactPlaylist` or something that uses `ReactPlayer` to play a list of URLs in sequence and provide methods for going back and forth.

**Comment by ravola** [comment] 2020-12-09 10:58
Understood! @cookpete
