### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by Tresky** [CookPete/react-player#508] opened 2018-10-26 19:48 UTC
I last worked on my project about a month ago. At that time, I was able to get Youtube videos to load and play properly in react-player. After coming back, I've discovered that something seems to have changed and now the video won't load. I end with the following error:
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://localhost:8000').
```
I've looked up some StackOverflow questions about it and I've read that it's an error coming from the Youtube iFrame API when you make a request for a Youtube video over http instead of https. I put some logging in the react-player library and saw that the requests are supposedly being made over https, so I don't think that's the issue I'm having here.

Does anyone have any insight into this?

As an aside, I'm using Gatsby as my platform. Not sure if this really matters.

**Comment by NathanielHill** [comment] 2018-10-29 15:10
I'm getting the same warning although the videos work, did you resolve it?

**Comment by lloydh** [comment] 2018-12-11 12:13
@Tresky I'm getting this too. Any tips on a fix?

**Comment by Tresky** [comment] 2018-12-13 18:16
@NathanielHill @lloydh Hey guys. Whenever I was working on this, I discovered that I get the error mentioned above, but the player still functions properly. I never found a solution to stop this error from appearing.

**Comment by carpben** [comment] 2019-01-15 14:49
I'm getting this error too. 
@CookPete , Are you aware of this issue? 
@Tresky , you closed the issue, even though it's relevant and hasn't been resolved. Do you mind reopening it? 
![image](https://user-images.githubusercontent.com/13496178/51187720-175c1980-18e5-11e9-9283-5b9535ceda32.png)

**Comment by Tresky** [comment] 2019-01-15 15:00
I've reopened this issue because it seems to be a common problem experienced by many people. Hopefully, we can find a solution here.

Does the issue happen only on page load? Do all postMessage events function properly after the initial page load? It could be that events are trying to be [posted to the hidden iframe before it gets loaded fully](https://stackoverflow.com/questions/22194409/failed-to-execute-postmessage-on-domwindow-the-target-origin-provided-does).

**Comment by CookPete** [comment] 2019-01-15 15:11
I'm aware of the issue, but afaik it's a problem with with the Youtube iFrame API based on whatever URL you are calling the API from, and it's not very consistent. This issue should remain closed unless there is a specific problem that ReactPlayer is causing.

There are plenty of mentions of the error elsewhere: https://www.google.com/search?q=youtube+iframe+Failed+to+execute+%27postMessage%27+on+%27DOMWindow%27%3A

However, ReactPlayer already tries to implement the solutions posted, eg [adding the `origin` property to the `playerVars`](https://github.com/CookPete/react-player/blob/a631f338d942712930a8d1829dec440731223b5e/src/players/YouTube.js#L53). Also note [this commit](https://github.com/CookPete/react-player/commit/c05bd9dff3a8595c5bb2e53c33ddaf8db8c894de) that pinned the API URL to `https` to try and prevent this issue.

If the error is still occurring (and not consistently) then I'm not sure what else can be done in this library.

**Comment by NathanielHill** [comment] 2019-01-15 15:33
This happens consistently on initial load for me. Is there another embedding technique? Having console errors lowers Lighthouse score which effects Google ranking.

**Comment by petrogad** [comment] 2019-02-08 15:49
Found something similar with Safari (on full screen) using vimeo. Getting a blocked a frame with origin error that I'm guessing is being thrown by postMessage.

It only happens in full screen though so I'm not entirely certain what to do.

**Comment by varajcs** [comment] 2019-02-27 13:26
for youtube -> try like this
config={
		{
		youtube: {
				playerVars: { controls: 1 ,origin: window.location.origin}
                 }
}
above code solved the problem for me

**Comment by jaotors** [comment] 2019-03-13 08:47
is there a way to fix this? what is the current progress of the investigation for this?

**Comment by CookPete** [comment] 2019-03-13 09:12
There is no investigation happening, unless someone else wants to try and figure it out. My [previous comment](https://github.com/CookPete/react-player/issues/508#issuecomment-454426112) pretty much sums it up. If it's a problem with the Youtube and Vimeo players, this issue should be closed as there is nothing to fix in this library. However, I'm happy to leave it open for the being for visibility, in case anyone wants to find out more.

**Comment by jaotors** [comment] 2019-03-13 11:38
@CookPete got it thanks.

So I found something interesting, upon using the `yt-player` library, well its the same implementation on this, but only on youtube, the player loads and its working, I think it loads upon re-rendering because I got this error. 
`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://localhost:3000').`

here is the code that i did on my project.
the videoId here is the videoId of the youtube and the `on` var is just for changing the tab.
btw what i do in here is that when you change the tab you just pause the current video.
`const ContentVideo = ({ videoId, on }) => {
  const player = useRef();

  useEffect(() => {
    player.current = new YTPlayer('#' + videoId);
    player.current.load(videoId);
  }, []);

  useEffect(() => {
    if (!on) {
      player.current.pause();
    }
  }, [on]);

  return (
    <div
      id={videoId}
      css={`
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        border: 0;
      `}
    />
  );
};`

I hope this will help.

**Closed** 2019-06-13 21:14 UTC

**Comment by papuruth** [comment] 2020-08-20 14:37
But if I'm embedding video like this there is no such error
<iframe width="560" height="315" src="https://www.youtube.com/embed/D6RtJLpdUgI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by Zhukreal** [comment] 2020-12-02 07:51
so, any solution here ?

**Comment by mixa9269** [comment] 2021-01-11 16:48
Any solutions?

**Comment by ronaklalwaniii** [comment] 2021-01-13 05:41
Any update?

**Comment by rtxvedant** [comment] 2021-02-08 19:29
help same issue ???

**Comment by linuz90** [comment] 2021-04-11 09:30
Also having this same issue, but oddly enough only on Android. It works perfectly on Chrome and Safari for Mac, and on iOS.

**Comment by phivh** [comment] 2021-06-23 16:26
I tried some cases and fix with this temp solution:
`
<ReactPlayer url={url} config={{
        youtube: {
         playerVars: { origin: 'https://www.youtube.com' }
      }
}}/>
`

**Comment by HectorLS** [comment] 2021-06-28 12:30
Im still having this issue with the last version.

Somehow @phivh config reduces the issue and now appears with less frencuency, but the bug its still happening

> I tried some cases and fix with this temp solution:
> `<ReactPlayer url={url} config={{ youtube: { playerVars: { origin: 'https://www.youtube.com' } } }}/>`

if someone finds out any workaround for a full fix, will be much appreciated if share here. 
Also i think this issue should be reopen.

**Comment by khvnkay** [comment] 2021-07-10 04:38
Any update?

**Comment by SebSnr** [comment] 2021-07-30 11:03
Any update ? Search since few hours but find no answer

Add this to my HTML, reduce errors count but not fix
		<script src="https://www.youtube.com/iframe_api"></script>
try but not fix
<ReactPlayer url={url} config={{ youtube: { playerVars: { origin: 'https://www.youtube.com' } } }}/>

**Comment by Parth909** [comment] 2021-11-05 17:33
The solution for this is to embed the url. This won't throw any errors

let video = "https://www.youtube.com/watch?v=AK-MUzWdpjU";

```js
video.includes("youtube") && (
                <iframe
                  className="w-auto sm:w-[80%] h-60 sm:h-80 sm:mx-4 sm:mb-4"
                  src={
                    video.includes("/watch?v=")
                      ? video.replace("/watch?v=", "/embed/")
                      : video
                  }
                  frameBorder="0"
                  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                  allowFullScreen
                ></iframe>
```

**Comment by ujnimz** [comment] 2022-02-09 13:33
Still facing this in 2022. Any fix?

**Comment by jslmariano** [comment] 2022-02-18 07:50
+1

**Comment by cookpete** [comment] 2022-02-19 12:57
I'm going to lock this issue because nothing useful is being added to the discussion. I am aware that the problem still happens. It sucks. But no-one is giving any more information on how to reproduce/debug/solve it.

If you really want this fixed, please read through [the many StackOverflow threads about this error](https://stackoverflow.com/search?q=Youtube+Failed+to+execute+postMessage+on+DOMWindow), and open a new issue with either a clear suggestion about what this library can do to fix the problem, or a clear way of reproducing the problem.
