### ISSUE TITLE
_this2.dash.getDebug(...).setLogToBrowserConsole is not a function

### ISSUE THREAD

**Issue by interpegasus** [CookPete/react-player#932] opened 2020-06-12 15:31 UTC
#### Current Behavior
Playback works but the console displays the following error during DASH playback.
_this2.dash.getDebug(...).setLogToBrowserConsole is not a function

#### Expected Behavior
No errors in console. And full support for DASH JS

#### Steps to Reproduce
```
                    <ReactPlayer
                        url="https://dash.akamaized.net/envivio/EnvivioDash3/manifest.mpd"
                        playing={true}
                        controls={true}
                        config={{
                            file: {
                                forceDASH: true,
                                dashVersion: "3.1.1",
                            },
                        }}
                    />
```

#### Environment
- URL attempting to play: https://dash.akamaized.net/envivio/EnvivioDash3/manifest.mpd
- Browser: Chrome
- Operating system: MAC OS

#### Other Information
Thanks

**Comment by afzaalahmad** [comment] 2020-06-12 16:05
It might be due to your version because I am unable to reproduce this.
here is the [sandbox](https://codesandbox.io/s/codealong-for-react-functional-components-otrpo) of your problem. no error in console.
try updating your version to latest.

**Comment by interpegasus** [comment] 2020-06-12 20:31
Thanks for the fast response. It looks like it is due to the Dash JS version.

setLogToBrowserConsole was deprecated and removed on version 3.

The issue is on Line 309 on FilePlayer.js

https://github.com/Dash-Industry-Forum/dash.js/issues/3018

<img width="1005" alt="Screen Shot 2020-06-12 at 3 31 00 PM" src="https://user-images.githubusercontent.com/934795/84543860-cad76200-acc1-11ea-8fc7-dbb3579bd41a.png">

**Comment by interpegasus** [comment] 2020-06-12 20:33
Currently I am using the npm version of react player:
```
"react-player": {
            "version": "2.3.0"

However the contents of the file FilePlayer.js in the npm packag look different from master branch. 
```

**Comment by interpegasus** [comment] 2020-06-12 20:36
However the contents of FilePlayer.js in the npm package look different from master branch...
<img width="1005" alt="Screen Shot 2020-06-12 at 3 31 00 PM" src="https://user-images.githubusercontent.com/934795/84544136-4cc78b00-acc2-11ea-827a-cc5db70478b7.png">

Line 147: https://github.com/CookPete/react-player/blob/master/src/players/FilePlayer.js

**Comment by CookPete** [comment] 2020-06-12 22:20
Fixed by https://github.com/CookPete/react-player/pull/933

**Closed by CookPete** 2020-06-12 22:20 UTC
