### ISSUE TITLE
onProgress is not being invoked

### ISSUE THREAD

**Issue by emidiotorre** [cookpete/react-player#1500] opened 2022-08-30 12:38 UTC
#### Current Behavior
the function assigned to the onProgress callback is not being called
#### Expected Behavior
I am trying to display the elapsed time, using the playedSeconds property on the state that should be passed to the onProgress callback

#### Steps to Reproduce
I am trying to play an audio file (.m4a)

**Comment by luciano-schirmer** [comment] 2022-08-30 23:39
I'm facing the same issue.

**Comment by luciano-schirmer** [comment] 2022-08-30 23:43
Downgrading to v2.10.0 solved the issue.

**Comment by luciano-schirmer** [comment] 2022-08-30 23:52
Quickly comparing v2.10.0 to v2.10.1, I suspect about the following added line:

https://github.com/cookpete/react-player/blob/9d4794137489c141cbffbdf2ddcdf5c2be803b2d/src/Player.js#L93

**Comment by dentsuALEXIS** [comment] 2022-08-31 07:44
The issue has been flagged here if you want more details https://github.com/cookpete/react-player/issues/1453

**Comment by cookpete** [comment] 2022-09-16 23:28
Fixed in `2.11.0`. Sorry for the delay.

**Closed by cookpete** 2022-09-16 23:28 UTC

**Comment by mustafaaden98** [comment] 2023-09-11 09:55
The issue is still not solved for mp4 video.
