### ISSUE TITLE
How can we make playing true to thumbnail which are .mp4 only when the video is in viewport?

### ISSUE THREAD

**Issue by Rajdeepc** [cookpete/react-player#1506] opened 2022-09-15 08:48 UTC
```
<ReactPlayer
              url={item.path}
              playing
              loop
              playsinline
              width='100%'
              height='100%'
              muted
              controls={false}
              className={styles.videoPlayer}
            />
```

On the above player which is on a list. I want to make  playing to be true only when 'item' is in viewport?
Can we directly control it via prop?

**Comment by cookpete** [comment] 2022-09-16 23:34
Duplicate of https://github.com/cookpete/react-player/issues/569

**Closed by cookpete** 2022-09-16 23:34 UTC
