### ISSUE TITLE
AES-128 with native hls

### ISSUE THREAD

**Issue by mjaafar1020** [cookpete/react-player#1441] opened 2022-04-20 10:18 UTC
We have a ReactJS application, we have a very customized hls.js and we use encryption.

Essentially hls.js isn't loading on safari/ios, meaning that our ios users aren't able to watch anything because all our videos are AES encrypted and the native safari player doesn't support encryption.

Is there any solution!!

**Comment by cookpete** [comment] 2022-05-02 21:50
Duplicate of https://github.com/cookpete/react-player/issues/1019

**Closed by cookpete** 2022-05-02 21:50 UTC
