### ISSUE TITLE
Youtube onSeek func not working

### ISSUE THREAD

**Issue by SenpaiKouhai** [cookpete/react-player#1243] opened 2021-05-29 07:47 UTC
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

nothing is happening on onSeek func
#### Expected Behavior

make something happen on onSeek func to get the real time and seeked time
#### Steps to Reproduce

1. Should be like this 
onSeek={ (e) => {
     // it should log something 
    console.log("seek func", e)
}}

#### Environment
- URL attempting to play:  youtube
- Browser: edge, chrome
- Operating system: windows
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

#### Other Information

Using Reactjs

**Comment by gatesyp** [comment] 2021-06-01 23:53
Your example is not working for me -- cannot reproduce

**Comment by SenpaiKouhai** [comment] 2021-06-05 07:15
@gatesyp  it seems that this func was removed by youtube only but on other player it works fine. The ways I did was created my own seekbar and just calling the seekTo() every time the user seeks on the video

**Comment by jedster1111** [comment] 2021-06-28 19:38
I'm seeing the same issue. Just in case it's handy, here's another basic reproduction: https://codesandbox.io/s/react-playground-forked-i2fw7?file=/index.js since the original seems broken.

**Comment by jedster1111** [comment] 2021-06-28 20:01
Also just noticed this is a duplicate of https://github.com/CookPete/react-player/issues/356 in which it was pointed out that this wasn't possible to achieve.

**Closed** 2024-04-20 12:31 UTC

**Comment by clementoriol** [comment] 2024-06-17 11:06
This has been closed as "completed" but from what I see this issue persist in `react-player@2.16.0`. 

What's your stance on adding this ? 
I know the YT player API does not have an "onSeek" event but there's been attempts by the react-player community to polyfill this (event a PR on this), and I think it would be a welcomed addition to the library, pushing forward the goal of harmonizing the various video providers API via react-player.

**Comment by carlosvalv** [comment] 2024-12-03 21:49
The only solution for me was to create a custom progress bar and do the onseek manually.
