### ISSUE TITLE
autoplay after onEnd

### ISSUE THREAD

**Issue by ioRekz** [CookPete/react-player#36] opened 2016-01-28 12:02 UTC
I'm trying to play the next song when one is finished.

I've added this to the onEnded prop but it only triggers when tab gain focus again.
The component is not created again, the iframe is not recreated.

This should work since the latest updates right ? 
I'm only trying on localhost (just stating in case chrome is allowing iframe on specific domain)

**Comment by CookPete** [comment] 2016-01-28 12:50
Hey @ioRekz, I'm assuming you are having this problem with the YouTube player. Have you tried using the [`preload`](https://github.com/CookPete/react-player#preloading) prop? This should fix the problem you are describing:
```js
<ReactPlayer
  url='https://www.youtube.com/watch?v=nySZH0tcL9I'
  youtubeConfig={{ preload: true }}
/>
```
See [the original PR](https://github.com/CookPete/react-player/pull/13) for more details.

**Comment by ioRekz** [comment] 2016-01-29 09:48
same result so far.
I only use youtube videos.
I'm also using the minified version from the library branch. Based on the PR details it could come from minification.

I was thinking that the onEnd callback could not be called when the tab is not focus but it is.
The video plays again as soon as the tab gains focus again.

**Comment by CookPete** [comment] 2016-02-26 09:57
@ioRekz could you post some code or an example repo where this happens? Or just some more detailed steps to reproduce the problem.

**Comment by CookPete** [comment] 2016-04-22 16:35
Closing this due to age. Feel free to re-open with steps to reproduce the issue.

**Closed by CookPete** 2016-04-22 16:35 UTC
