### ISSUE TITLE
Markers

### ISSUE THREAD

**Issue by marksteven** [cookpete/react-player#1493] opened 2022-08-21 13:32 UTC
Hopefully simple question

Is it possible to add markers to a video window (marker to click progress bar or show a highlight on a video at 1min 2 min etc) 
and if so what package (if any) is recommended.
thanks in advance Pete
Cheers

**Comment by cookpete** [comment] 2022-08-31 11:34
Duplicate of #713 and #821

**Closed by cookpete** 2022-08-31 11:34 UTC
