### ISSUE TITLE
React Minified errors #423 & #418

### ISSUE THREAD

**Issue by joebentaylor1995** [cookpete/react-player#1602] opened 2023-03-23 13:26 UTC
After commenting out code until i found the culprit in my GatsbyJS project it turns out its the React-Player component.

Here is my code, in case im doing something wrong.
```
// Imports
// ------------
import React, { useLayoutEffect, useRef } from 'react';
import ReactPlayer from 'react-player/file';
import { useDato } from './data';
import { useBreakpoint } from 'gatsby-plugin-breakpoints';

// Styles
// ------------
import { Jacket, Overlay } from './styles';

// Component
// ------------
const VideoBackground = () => {
    // NOTE • Data
    const { desktop, mobile } = useDato();

    // NOTE • Refs
    const main = useRef();
    const bg = useRef();

    // NOTE • Breakpoints
    const bp = useBreakpoint();

    const videoToUse = bp.large ? desktop : mobile;


    return (
        <Jacket ref={main} id="video">
            <Overlay ref={bg} id="video-overlay" />

            <ReactPlayer
                url={videoToUse}
                loop
                playing
                muted
                width="100%"
                height="100%"
            />
        </Jacket>
    );
}

export default VideoBackground;
```

The second i remove the `ReactPlayer`, the error has gone.

The error im getting is:
```
react-dom.production.min.js:131 Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at sa (react-dom.production.min.js:131:278)
    at xi (react-dom.production.min.js:293:379)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at gs (react-dom.production.min.js:280:180)
    at as (react-dom.production.min.js:268:209)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
sa @ react-dom.production.min.js:131
xi @ react-dom.production.min.js:293
ks @ react-dom.production.min.js:280
ys @ react-dom.production.min.js:280
gs @ react-dom.production.min.js:280
as @ react-dom.production.min.js:268
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
react-dom.production.min.js:293 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at xi (react-dom.production.min.js:293:39)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at gs (react-dom.production.min.js:280:180)
    at os (react-dom.production.min.js:271:88)
    at as (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
```

Packages:
```
	"dependencies": {
		"babel-plugin-styled-components": "2.0.7",
		"gatsby": "^5.8.0",
		"gatsby-plugin-alias-imports": "1.0.5",
		"gatsby-plugin-breakpoints": "1.3.9",
		"gatsby-plugin-image": "^3.8.0",
		"gatsby-plugin-layout": "^4.8.0",
		"gatsby-plugin-manifest": "^5.8.0",
		"gatsby-plugin-netlify": "5.1.0",
		"gatsby-plugin-sharp": "^5.8.0",
		"gatsby-plugin-styled-components": "^6.8.0",
		"gatsby-source-datocms": "5.0.4",
		"gatsby-transformer-sharp": "^5.8.0",
		"gsap": "npm:@gsap/business@3.11.4",
		"mobx": "^6.8.0",
		"mobx-react-lite": "^3.4.3",
		"prop-types": "^15.8.1",
		"react": "18.2.0",
		"react-dom": "18.2.0",
		"react-hotkeys-hook": "^4.3.8",
		"react-mailchimp-subscribe": "^2.1.3",
		"react-player": "2.12.0",
		"react-use": "17.4.0",
		"styled-components": "5.3.9"
	},
```

This is causing my Best practices lighthouse score to drop from 100 to 92

**Comment by cookpete** [comment] 2023-03-24 23:14
Duplicate of #1428 and/or #1474 I think?

**Closed by cookpete** 2023-03-24 23:14 UTC

**Comment by joebentaylor1995** [comment] 2023-03-24 23:20
Looks related, im unsure
