### ISSUE TITLE
Request to support controlslist

### ISSUE THREAD

**Issue by JenniferFuBook** [CookPete/react-player#889] opened 2020-05-15 03:39 UTC
#### Current Behavior
controlslist is not supported.

#### Expected Behavior
controlslist is supported to configure controls.

**Comment by CookPete** [comment] 2020-05-15 04:47
Duplicate of https://github.com/CookPete/react-player/issues/232. Please search for your issue before creating another.

**Closed by CookPete** 2020-05-15 04:47 UTC
