### ISSUE TITLE
add bookmark or note at video 

### ISSUE THREAD

**Issue by discriminant-tech** [CookPete/react-player#928] opened 2020-06-11 13:00 UTC
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
any possibility to add  functionality show at image 
#### Expected Behavior
![image](https://user-images.githubusercontent.com/54133747/84387967-6ceb4180-ac11-11ea-86f4-ab626f69c419.png)

**Comment by CookPete** [comment] 2020-06-11 19:40
Feels like a duplicate of https://github.com/CookPete/react-player/issues/821. ReactPlayer does not have any custom controls. There is nothing stopping you from building your own, however.

**Closed by CookPete** 2020-06-11 19:40 UTC
