### ISSUE TITLE
Soundcloud playback in chrome on android hangs indefinitely 

### ISSUE THREAD

**Issue by jake-g** [CookPete/react-player#103] opened 2016-09-07 04:53 UTC
Is it just me? Youtube links will play fine, but soundcloud links dont on chrome for android. Tested with my own application and rplayr.com.

I briefly browsed other issues and it seems this hasn't been reported.

I could set up remote debugging to look deeper if it would help

**Comment by CookPete** [comment] 2016-09-07 07:37
Hey @jake-g, any console errors or output would indeed be helpful as I have no android devices to test with.

**Comment by jake-g** [comment] 2016-09-07 18:10
![image](https://cloud.githubusercontent.com/assets/10370530/18323045/9d96dfae-74ea-11e6-828b-a1e44ed77923.png)

Inspector on android. Looks like the gesture isn't recognized when a soundcloud link is clicked? Any ideas?

**Comment by jake-g** [comment] 2016-09-15 17:16
happy to help but pretty usnsure where to start. does this give you any sort of clue cookpete?

**Comment by CookPete** [comment] 2016-09-15 17:26
The problem is that android is trying to be too clever to prevent autoplaying audio. On the click event, the component will [resolve the soundcloud track](https://github.com/CookPete/react-player/blob/master/src/players/SoundCloud.js#L41) and _then_ set the `src` and _then_ play the audio when the `onReady` function is called. Because of this delay, Android is just giving up and assuming the browser is trying to autoplay something.

**Comment by CookPete** [comment] 2016-09-15 19:34
[This guy's solution](http://stackoverflow.com/a/32571967) to the problem is to play a tiny, silent sound on the click event to "prime" the player. This could be a possible solution for `ReactPlayer` too.

**Comment by jake-g** [comment] 2017-01-05 05:44
So I did get around to trying to fix. I cloned rplayr and was able to identify SoundCloud tracks when clicked, but didn't manage to splice in a local sound file, THEN play the Soundcloud link once it resolved. I tried, but my understanding of the async calls and how react-sound works isn't enough to get this hack working.

It's difficult to test since the bug is only on mobile phones and I'm trying to fix on my mac. I used an audible sound for now as my buffer sound, but when testing, never actually hear it, rplayr just loads the SoundCloud link and skips my attempt. For reference, http://duramecho.com/Misc/SilentCd/ has already made silence mp3s, but if anyone tries to test you may want a more audible sound to guarantee it plays.

I attempted my hack in the Playlist.js section of rplayr in the playPost = (post) => ... function. Perhaps it would be better long term to put the fix in react-player such that if mobile and if the Soundcloud link, insert the sound clip...

For now, in my project, i am just skipping Soundcloud links if mobile so the site doesn't hang. I think this issue exists on ios too, or maybe just chrome ios...I only tested briefly

Hopefully, we can work towards a better fix, but I'm not the best person for the job. I see how it may not be a priority as well.

**Comment by CookPete** [comment] 2017-04-27 14:08
This looks like a restriction of the Android browser with `<audio>` elements and not an issue with ReactPlayer itself. Closing for now.

**Closed by CookPete** 2017-04-27 14:08 UTC
